# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-13 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('league_id', models.AutoField(primary_key=True, serialize=False)),
                ('league_name', models.TextField()),
                ('num_teams', models.IntegerField()),
            ],
            options={
                'db_table': 'leagues',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('team', models.TextField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=25, null=True)),
                ('health', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.TextField()),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('matchup_id', models.AutoField(primary_key=True, serialize=False)),
                ('week_num', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('home_points', models.IntegerField(blank=True, null=True)),
                ('away_points', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.TextField()),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('ties', models.IntegerField(blank=True, null=True)),
                ('points_for', models.IntegerField(blank=True, null=True)),
                ('points_against', models.IntegerField(blank=True, null=True)),
                ('standings_points', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
                ('pword', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='GoalieStatsGame',
            fields=[
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='nwhl_fantasy.Players')),
                ('goals', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('pen_mins', models.IntegerField(blank=True, null=True)),
                ('goals_against', models.IntegerField(blank=True, null=True)),
                ('shots_against', models.IntegerField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('ties', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goalie_stats_game',
            },
        ),
        migrations.CreateModel(
            name='GoalieStatsSeason',
            fields=[
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='nwhl_fantasy.Players')),
                ('goals_against', models.IntegerField(blank=True, null=True)),
                ('shots_against', models.IntegerField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('ties', models.IntegerField(blank=True, null=True)),
                ('games_played', models.IntegerField(blank=True, null=True)),
                ('saves', models.IntegerField(blank=True, null=True)),
                ('shoot_out_losses', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goalie_stats_season',
            },
        ),
        migrations.CreateModel(
            name='SkaterStatsMatchup',
            fields=[
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='nwhl_fantasy.Players')),
                ('goals', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('plus_minus', models.IntegerField(blank=True, null=True)),
                ('pen_mins', models.IntegerField(blank=True, null=True)),
                ('power_play_goals', models.IntegerField(blank=True, null=True)),
                ('power_play_assists', models.IntegerField(blank=True, null=True)),
                ('shorthanded_goals', models.IntegerField(blank=True, null=True)),
                ('shorthanded_assists', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'skater_stats_matchup',
            },
        ),
        migrations.CreateModel(
            name='SkaterStatsSeason',
            fields=[
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='nwhl_fantasy.Players')),
                ('goals', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('plus_minus', models.IntegerField(blank=True, null=True)),
                ('pen_mins', models.IntegerField(blank=True, null=True)),
                ('power_play_goals', models.IntegerField(blank=True, null=True)),
                ('power_play_assists', models.IntegerField(blank=True, null=True)),
                ('short_handed_goals', models.IntegerField(blank=True, null=True)),
                ('short_handed_assists', models.IntegerField(blank=True, null=True)),
                ('games_played', models.IntegerField(blank=True, null=True)),
                ('sog', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('faceoffs_won', models.IntegerField(blank=True, null=True)),
                ('faceoffs_lost', models.IntegerField(blank=True, null=True)),
                ('blocked_shots', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'skater_stats_season',
            },
        ),
        migrations.AddField(
            model_name='teams',
            name='bench1',
            field=models.ForeignKey(blank=True, db_column='bench1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_player_id_bench1', to='nwhl_fantasy.Players'),
        ),
        migrations.AddField(
            model_name='teams',
            name='bench2',
            field=models.ForeignKey(blank=True, db_column='bench2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_player_id_bench2', to='nwhl_fantasy.Players'),
        ),
        migrations.AddField(
            model_name='teams',
            name='bench3',
            field=models.ForeignKey(blank=True, db_column='bench3', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_player_id_bench3', to='nwhl_fantasy.Players'),
        ),
        migrations.AddField(
            model_name='teams',
            name='bench4',
            field=models.ForeignKey(blank=True, db_column='bench4', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_player_id_bench4', to='nwhl_fantasy.Players'),
        ),
        migrations.AddField(
            model_name='teams',
            name='def1',
            field=models.ForeignKey(blank=True, db_column='def1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_player_id_def1', to='nwhl_fantasy.Players'),
        ),
        migrations.AddField(
            model_name='teams',
            name='def2',
            field=models.ForeignKey(blank=True, db_column='def2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_player_id_def2', to='nwhl_fantasy.Players'),
        ),
        migrations.AddField(
            model_name='teams',
            name='fwd1',
            field=models.ForeignKey(blank=True, db_column='fwd1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_player_id_fwd1', to='nwhl_fantasy.Players'),
        ),
        migrations.AddField(
            model_name='teams',
            name='fwd2',
            field=models.ForeignKey(blank=True, db_column='fwd2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_player_id_fwd2', to='nwhl_fantasy.Players'),
        ),
        migrations.AddField(
            model_name='teams',
            name='fwd3',
            field=models.ForeignKey(blank=True, db_column='fwd3', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_player_id_fwd3', to='nwhl_fantasy.Players'),
        ),
        migrations.AddField(
            model_name='teams',
            name='goalie',
            field=models.ForeignKey(blank=True, db_column='goalie', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_player_id_goalie', to='nwhl_fantasy.Players'),
        ),
        migrations.AddField(
            model_name='teams',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nwhl_fantasy.Leagues'),
        ),
        migrations.AddField(
            model_name='teams',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nwhl_fantasy.Users'),
        ),
        migrations.AddField(
            model_name='teams',
            name='util',
            field=models.ForeignKey(blank=True, db_column='util', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams_player_id_util', to='nwhl_fantasy.Players'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='away_team',
            field=models.ForeignKey(blank=True, db_column='away_team', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nwhl_fantasy.Teams'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='home_team',
            field=models.ForeignKey(blank=True, db_column='home_team', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedules_team_id', to='nwhl_fantasy.Teams'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nwhl_fantasy.Leagues'),
        ),
        migrations.AddField(
            model_name='skaterstatsmatchup',
            name='matchup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nwhl_fantasy.Schedules'),
        ),
        migrations.AddField(
            model_name='goaliestatsgame',
            name='matchup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nwhl_fantasy.Schedules'),
        ),
    ]
